name: nextflow-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow>=23.0
  - python>=3.10
  - matplotlib>=3.8
  - fastqc=0.12.1
  - trimmomatic=0.39
  - megahit=1.2.9
  - bwa=0.7.17
  - samtools=1.19
  - sra-tools=3.1.0
