name: hw3-pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow>=23.0
  - python>=3.10
  - matplotlib>=3.8
  - fastqc
  - trimmomatic
  - megahit
  - seqtk
  - bwa
  - samtools
  - bcftools
  - sra-tools
